/**
 * Danh mục 25 Câu Lạc Bộ Chính Thức tại Đại học FPT Đà Nẵng
 * Tích hợp Logo chính thức từ Google Drive & Backdrop 3mx3m từ dữ liệu Ngày hội CLB
 */
export const FPTU_CLUBS = {
  // --- HỌC THUẬT: CÔNG NGHỆ ---
  itsc: {
    id: 'itsc',
    prefix: 'ITSC',
    nameEn: 'Innovative Technology Student Club',
    nameVi: 'CLB Công nghệ đổi mới',
    group: 'Học thuật',
    subgroup: 'Công nghệ',
    boothNumber: 10,
    floor: 2,
    themeColor: '#38bdf8',
    icon: '💻',
    logoId: '11U9X13jIp9iiuZUbXpyf1EiGPDfjLqse',
    logoUrl: '/assets/clubs/logos/itsc.png',
    backdropId: '1Ta60OktZ7g-DvwX1egXz-5wvJUR3Dn7b',
    backdropLocalPath: '/assets/clubs/backdrops/itsc_backdrop.png',
    slogan: 'Innovation Beyond Limits',
    description: 'Nghiên cứu và ứng dụng các công nghệ tiên phong: AI Agents, Cloud Computing, IoT, phát triển giải pháp thực tiễn cho sinh viên và doanh nghiệp.',
    props: 'Kính AR/VR, LED, Tablet',
    costume: 'Áo CLB và Quần tự do',
    videoConcept: 'Nhân vật đeo kính → thế giới ảo hiện ra',
    officer: 'AnhTD',
    memberCount: 30,
    leads: 'Nguyễn Đình Hoàng (0362930109), Nguyễn Đình Mai Thy (0762514818), Phan Vũ Ý Nhi (0905859003)',
    activities: [
      'Workshop chuyên sâu về AI & Điện toán đám mây',
      'Đào tạo GenAI & Hackathon đổi mới sáng tạo',
      'Dự án hợp tác công nghệ liên CLB (ITSC x FU-DEVER)'
    ],
    roles: 'Lập trình viên, Nhà nghiên cứu AI, Quản trị hệ thống Cloud'
  },
  src: {
    id: 'src',
    prefix: 'SRC',
    nameEn: 'Security Research Club',
    nameVi: 'CLB An toàn thông tin',
    group: 'Học thuật',
    subgroup: 'Công nghệ',
    boothNumber: 15,
    floor: 2,
    themeColor: '#ef4444',
    icon: '🛡️',
    logoId: '1glNhUNkPV_ph4NEByyDk1H94MfORViF3',
    logoUrl: '/assets/clubs/logos/src.png',
    backdropId: '1hnw_UMJng07E_7dqgwM80sFD1Ay_ruEy',
    backdropLocalPath: '/assets/clubs/backdrops/src_backdrop.png',
    slogan: 'Defend & Conquer The Cyberspace',
    description: 'Cái nôi của các Cyber Warriors FPTU Đà Nẵng, chuyên sâu về An toàn thông tin, Capture The Flag (CTF), điều tra số và bảo mật mạng.',
    props: 'Laptop + Màn hình Code, Khóa, USB, Kính bảo hộ',
    costume: 'Áo CLB và Quần tự do',
    videoConcept: 'Gõ code → màn hình hiện cảnh báo đỏ',
    officer: 'HoaNT',
    memberCount: 26,
    leads: 'Nguyễn Văn Thịnh (0815204928), Huỳnh Ngọc Hiếu (0703577614), Trần Thị Ngọc Huyền (0905705993)',
    activities: [
      'Tập luyện và thi đấu các giải CTF trong nước và quốc tế',
      'Nghiên cứu lỗ hổng bảo mật, Pentest và phân tích mã độc',
      'Chia sẻ kiến thức bảo mật số cho cộng đồng sinh viên'
    ],
    roles: 'Pentesters, CTF Players, Security Analysts'
  },
  dever: {
    id: 'dever',
    prefix: 'DEVER',
    nameEn: 'Developer Club',
    nameVi: 'CLB Lập trình FU-DEVER',
    group: 'Học thuật',
    subgroup: 'Công nghệ',
    boothNumber: 5,
    floor: 2,
    themeColor: '#f97316',
    icon: '🚀',
    logoId: '1X_Yqyq9DUuiGA2PladTr7Q56UkAJml5G',
    logoUrl: '/assets/clubs/logos/dever.png',
    backdropId: '10WM0HUFC8U8simLJr_TP9etMxZo1CFXt',
    backdropLocalPath: '/assets/clubs/backdrops/dever_backdrop.png',
    slogan: 'Code. Ship. Scale.',
    description: 'CLB Kỹ thuật phần mềm hàng đầu FPTU Đà Nẵng với 4 phân ban (Web, AI, Mobile, Game). Xây dựng sản phẩm thực tế, đào tạo mentor 1:1 và tổ chức Hackathon.',
    props: 'Bàn phím cơ, chuột, laptop',
    costume: 'Áo CLB và Quần đen',
    videoConcept: 'Tay code cực nhanh → camera push-in vào màn hình',
    officer: 'DiuVT',
    memberCount: 38,
    leads: 'Nguyễn Thái Hưng (0353345206), Đặng Quang Nhật (0377231436), Phan Tuấn Hưng (0395936201)',
    activities: [
      'Phát triển thế giới ảo DEVER TOWN & các dự án mã nguồn mở',
      'Đào tạo lập trình thực chiến Full-stack, AI, Mobile, Game',
      'Chuỗi sự kiện Hacknight, Tech Workshops & Hackathon'
    ],
    roles: 'Full-Stack Developers, AI Engineers, Game Devs, Designers'
  },

  // --- HỌC THUẬT: KINH TẾ & KHỞI NGHIỆP ---
  resup: {
    id: 'resup',
    prefix: 'RESUP',
    nameEn: 'Research & StartUp',
    nameVi: 'CLB Nghiên cứu và Khởi nghiệp',
    group: 'Học thuật',
    subgroup: 'Kinh tế',
    boothNumber: 24,
    floor: 2,
    themeColor: '#10b981',
    icon: '🌱',
    logoId: '17F1VsjTiO8sY0Ifh17sqI_JB6l0VAUdx',
    logoUrl: '/assets/clubs/logos/resup.png',
    backdropUrl: 'https://drive.google.com/drive/folders/1aQeum9DRt3yVoB8nq9itED-4AqiPVe9p',
    slogan: 'From Ideas to Reality',
    description: 'Cộng đồng ươm mầm các ý tưởng kinh doanh và nghiên cứu khoa học, kết nối sinh viên đam mê khởi nghiệp với các nhà đầu tư và mentor doanh nghiệp.',
    props: 'Prototype/mô hình sản phẩm, Sticky note, bản vẽ, kính',
    costume: 'Áo CLB và quần tự do',
    videoConcept: 'Nhân vật ghép các mảnh prototype → thành sản phẩm',
    officer: 'HoaNT',
    memberCount: 30,
    leads: 'Nguyễn Đỗ Thanh Uyên (0932191821), Trần Ngọc Linh Chi (0909902288), Hà Đặng Minh Phúc (0961012260)',
    activities: [
      'Phát triển mô hình kinh doanh Canvas & Pitching thực chiến',
      'Hỗ trợ dự án tham gia các cuộc thi khởi nghiệp sinh viên',
      'Tọa đàm gặp gỡ các Founders & CEOs'
    ],
    roles: 'Project Managers, Business Analysts, Researchers'
  },
  fic: {
    id: 'fic',
    prefix: 'FIC',
    nameEn: 'Financial Investing Club',
    nameVi: 'CLB Tài chính & Đầu tư',
    group: 'Học thuật',
    subgroup: 'Kinh tế',
    boothNumber: 4,
    floor: 2,
    themeColor: '#f59e0b',
    icon: '📈',
    logoId: '17f8IVgIwdUFfYQHws0dHG8_IMTLNtk8o',
    logoUrl: '/assets/clubs/logos/fic.png',
    backdropId: '1d9ZlaYR2YPhh98h1srEZWlCNAaDOnl1K',
    backdropLocalPath: '/assets/clubs/backdrops/fic_backdrop.png',
    slogan: 'Master Your Financial Future',
    description: 'Nơi quy tụ các tài năng trẻ đam mê thị trường tài chính, chứng khoán, quản trị rủi ro và hoạch định tài chính cá nhân chuyên nghiệp.',
    props: 'Tiền xu / tiền giả',
    costume: 'Áo CLB, Quần đen, có thể có Blazer, vest',
    videoConcept: 'Tung đồng xu quyết định đầu tư',
    officer: 'DiuVT',
    memberCount: 11,
    leads: 'Nguyễn Văn Bảo Ngọc (0367505263), Lê Trần Bảo Nguyên (0944888201), Nguyễn Tiến Đạt (0912177540)',
    activities: [
      'Phân tích kỹ thuật & kinh tế vĩ mô',
      'Mô phỏng sàn giao dịch chứng khoán sinh viên',
      'Quản lý danh mục đầu tư và tài chính cá nhân'
    ],
    roles: 'Financial Analysts, Risk Managers, Market Researchers'
  },
  tss: {
    id: 'tss',
    prefix: 'TSS',
    nameEn: 'FU Startup Club',
    nameVi: 'CLB Khởi nghiệp Trẻ FPTU',
    group: 'Học thuật',
    subgroup: 'Kinh tế',
    boothNumber: 13,
    floor: 2,
    themeColor: '#6366f1',
    icon: '💡',
    logoId: '1_YX8Su8nJAkEFgavthWlxirYkvT26eb_',
    logoUrl: '/assets/clubs/logos/tss.png',
    backdropId: '1xNaEihiab79DYsYj426vsxGJKtz0qfoM',
    backdropLocalPath: '/assets/clubs/backdrops/tss_backdrop.png',
    slogan: 'Ignite The Startup Spark',
    description: 'Môi trường thúc đẩy tinh thần đổi mới sáng tạo, hiện thực hóa các ý tưởng kinh doanh sinh viên thành các startup có giá trị thương mại.',
    props: 'Pitch deck / bảng ý tưởng, Laptop, mockup sản phẩm',
    costume: 'Áo CLB và Quần sẫm màu',
    videoConcept: 'Đập tay xuống bàn → Tên CLB xuất hiện',
    officer: 'DiuVT',
    memberCount: 15,
    leads: 'Trần Đỗ Uyên Phương (0373899856), Hồ Quang Triều (0376521077), Nguyễn Đình Nam Tú (0913311952)',
    activities: [
      'Vườn ươm dự án khởi nghiệp tiềm năng',
      'Networking với hệ sinh thái khởi nghiệp miền Trung',
      'Workshop kỹ năng kêu gọi vốn và xây dựng MVP'
    ],
    roles: 'Co-Founders, Marketers, Product Builders'
  },

  // --- HỌC THUẬT: NGÔN NGỮ & VĂN HÓA ---
  mirai_jc: {
    id: 'mirai_jc',
    prefix: 'MIRAI-JC',
    nameEn: 'Mirai Japanese Club',
    nameVi: 'CLB Ngôn ngữ và Văn hoá Nhật Bản',
    group: 'Học thuật',
    subgroup: 'Ngôn ngữ',
    boothNumber: 16,
    floor: 2,
    themeColor: '#ec4899',
    icon: '🌸',
    logoId: '143P4bayMrkbOXJeM9c6Jm5Yyk-GExEFH',
    logoUrl: '/assets/clubs/logos/mirai_jc.png',
    backdropId: '1tXhl9BmB3RZ252LkWNcmvuhMIT4VWxw_',
    backdropLocalPath: '/assets/clubs/backdrops/mirai_jc_backdrop.png',
    slogan: 'Chạm Vào Văn Hóa Xứ Sở Hoa Anh Đào',
    description: 'Giao lưu văn hóa Nhật Bản, rèn luyện tiếng Nhật giao tiếp, cosplay, lễ hội truyền thống và cơ hội làm việc tại các doanh nghiệp Nhật Bản.',
    props: 'Đồ Nhật bản, Kendama',
    costume: 'Đồ Nhật bản, Kimono / Yukata',
    videoConcept: 'Một lần tung Kendama thành công → tên CLB xuất hiện',
    officer: 'HoaNT',
    memberCount: 38,
    leads: 'Dương Duy Vinh (0946010230), Lê Văn Huy (0943169123), Phạm Vũ Hoàng Quân (0949057003)',
    activities: [
      'Lễ hội văn hóa Nhật Bản (Bunkasai, Tanabata)',
      'Lớp học hội thoại tiếng Nhật từ N5 đến N2',
      'Workshop Trà đạo, Thư pháp & Cosplay'
    ],
    roles: 'Biên dịch viên, MC tiếng Nhật, Ban Sự kiện Văn hóa'
  },
  fkc: {
    id: 'fkc',
    prefix: 'FKC',
    nameEn: 'FPT Korean Club',
    nameVi: 'CLB Tiếng Hàn & Văn Hóa Hàn Quốc',
    group: 'Học thuật',
    subgroup: 'Ngôn ngữ',
    boothNumber: 25,
    floor: 2,
    themeColor: '#06b6d4',
    icon: '🇰🇷',
    logoId: '13pxYVyvs9obzGBhVCAKKD3js7kpZ6Foj',
    logoUrl: '/assets/clubs/logos/fkc.png',
    backdropId: '1GZBfIvjg4er-OQ_L0rT-6z1pee9Rh-kl',
    backdropLocalPath: '/assets/clubs/backdrops/fkc_backdrop.png',
    slogan: 'K-Wave & Language Passion',
    description: 'Cộng đồng những bạn trẻ đam mê ngôn ngữ, âm nhạc, điện ảnh và văn hóa Hàn Quốc, tạo môi trường học tập và trải nghiệm năng động.',
    props: 'Hanbok / quạt Hàn, Cờ Hàn, sách tiếng Hàn',
    costume: 'Đồ hanbok truyền thống',
    videoConcept: 'Xòe quạt → whip pan chuyển cảnh',
    officer: 'AnhTD',
    memberCount: 9,
    leads: 'Lê Thuỷ Tiên (0326209145), Huỳnh Thị Mỹ Tâm (0352210421), Võ Thị Thanh Thảo (0702115499)',
    activities: [
      'CLB học tiếng Hàn giao tiếp và ôn thi TOPIK',
      'Giao lưu văn hóa K-Pop, ẩm thực Hàn Quốc',
      'Sự kiện trải nghiệm Hanbok và trò chơi truyền thống'
    ],
    roles: 'Giao lưu ngôn ngữ, Biên tập viên nội dung, Điều phối viên'
  },
  fucc: {
    id: 'fucc',
    prefix: 'FUCC',
    nameEn: 'FUDA Chinese Club',
    nameVi: 'CLB Tiếng Trung & Hán Ngữ',
    group: 'Học thuật',
    subgroup: 'Ngôn ngữ',
    boothNumber: 7,
    floor: 2,
    themeColor: '#dc2626',
    icon: '🏮',
    logoId: '15b_qRImBkYBeHsuiLNScm6k5Q0j-FYpQ',
    logoUrl: '/assets/clubs/logos/fucc.png',
    backdropId: '10nNr7jYmiKO29S6eOw9GHU_2PJVR2ixD',
    backdropLocalPath: '/assets/clubs/backdrops/fucc_backdrop.png',
    slogan: 'Kết Nối Văn Hóa Phương Đông',
    description: 'Không gian học tập tiếng Trung, giao lưu văn hóa Trung Hoa, luyện thi HSK và tìm hiểu cơ hội du học, việc làm đa quốc gia.',
    props: 'Thư pháp + bút lông, Đèn lồng đỏ, cuộn giấy',
    costume: 'Cổ trang Trung Quốc',
    videoConcept: 'Viết một nét thư pháp → nét mực biến thành đường sáng',
    officer: 'HoaNT',
    memberCount: 18,
    leads: 'Hoàng Lê Anh Nguyên (0916763146), Phùng Thị Ngọc Duyên (0366696507)',
    activities: [
      'Góc đàm thoại tiếng Trung mỗi tuần',
      'Giao lưu văn hóa Hán tự, Trà nghệ, Lễ hội Trung Thu',
      'Tập huấn phát âm chuẩn và kỹ năng dịch thuật'
    ],
    roles: 'Biên dịch viên, Tác giả content, Điều phối viên văn hóa'
  },

  // --- KỸ NĂNG & SÁNG TẠO ---
  fcs: {
    id: 'fcs',
    prefix: 'FCS',
    nameEn: "FUDA's Creative Space",
    nameVi: 'Không gian Sáng tạo',
    group: 'Kỹ Năng',
    subgroup: 'Thiết kế',
    boothNumber: 20,
    floor: 3,
    themeColor: '#8b5cf6',
    icon: '🎨',
    logoId: '11ouniBzsNozqgeFyHnjUbRCbVIJg5bH5',
    logoUrl: '/assets/clubs/logos/fcs.png',
    backdropId: '1zSrnCGnRyt3AN7_S8JFwr3Jopxe7R04c',
    backdropLocalPath: '/assets/clubs/backdrops/fcs_backdrop.png',
    slogan: 'Unleash Your Creative Power',
    description: 'Ngôi nhà chung của các Designer, Illustrator và người yêu nghệ thuật thị giác tại FPTU Đà Nẵng. Nơi biến trí tưởng tượng thành các ấn phẩm đỉnh cao.',
    props: 'Bộ đàm, Vé, dây đeo, bảng event, Bảng idea',
    costume: 'Quần đen & Áo CLB',
    videoConcept: 'Bảng idea phác thảo sáng tạo bay bổng',
    officer: 'DiuVT',
    memberCount: 37,
    leads: 'Đỗ Thế Huy (0915790595), Lê Nguyễn Phương Thảo (0981596455), Trần Nữ Vân Khoa (0941577438)',
    activities: [
      'Workshop UI/UX, Graphic Design, 3D Modeling',
      'Triển lãm nghệ thuật số & thiết kế sinh viên',
      'Thiết kế bộ nhận diện sự kiện cho trường'
    ],
    roles: 'Graphic Designers, UI/UX Designers, Illustrators'
  },
  fum: {
    id: 'fum',
    prefix: 'FUM',
    nameEn: 'Media Club',
    nameVi: 'CLB Truyền thông FPTU',
    group: 'Kỹ Năng',
    subgroup: 'Truyền thông',
    boothNumber: 1,
    floor: 3,
    themeColor: '#f43f5e',
    icon: '📸',
    logoId: '1fXmhw6TbUqDHU1q_f4xRljvIm6WOhs-q',
    logoUrl: '/assets/clubs/logos/fum.png',
    backdropId: '1yUfmfT-PwNUmazxUVDMHaM5DRO358T7A',
    backdropLocalPath: '/assets/clubs/backdrops/fum_backdrop.png',
    slogan: 'Tell Stories Through The Lens',
    description: 'Đội ngũ phụ trách ghi lại những khoảnh khắc đẹp nhất của sinh viên FPTU, chuyên nghiệp trong nhiếp ảnh, quay dựng video và quản trị kênh truyền thông.',
    props: 'Máy ảnh, Gimbal, Laptop, Kẹp file',
    costume: 'Quần đen & Áo CLB',
    videoConcept: 'Camera quay thẳng POV nhân vật',
    officer: 'AnhTD',
    memberCount: 29,
    leads: 'Huỳnh Vĩnh Uyên (0981431506), Phan Văn Hợp (0968993669), Vạn Hồ Châu Anh (0859180419)',
    activities: [
      'Bắt trọn khoảnh khắc tại mọi sự kiện lớn nhỏ của trường',
      'Sản xuất Video Viral, Phim ngắn sinh viên & Podcast',
      'Đào tạo kỹ năng máy ảnh, ánh sáng và hậu kỳ Premiere/After Effects'
    ],
    roles: 'Photographers, Videographers, Video Editors, Content Creators'
  },
  evo: {
    id: 'evo',
    prefix: 'EVo',
    nameEn: "FUDA's Event Club",
    nameVi: 'CLB Sự kiện FPTU',
    group: 'Kỹ Năng',
    subgroup: 'Sự kiện',
    boothNumber: 23,
    floor: 3,
    themeColor: '#0ea5e9',
    icon: '🎉',
    logoId: '1UeAM_uAQ6nxmFXAEcv4N9Hm9zwkqGH4Z',
    logoUrl: '/assets/clubs/logos/evo.png',
    backdropId: '1XqMAtr6tyRFknrbtS7n1b9NUQVgli33U',
    backdropLocalPath: '/assets/clubs/backdrops/evo_backdrop.png',
    slogan: 'Mastermind Behind Big Moments',
    description: 'Những con người đứng sau thành công của các đại nhạc hội, ngày hội Club Day, Prom Night và các sự kiện quy mô hàng ngàn sinh viên tại FPTU.',
    props: 'Bộ đàm, Vé, dây đeo, bảng event',
    costume: 'Áo CLB và Quần đen',
    videoConcept: 'Bộ đàm vang lên → nhân vật chạy vào frame',
    officer: 'HoaNT',
    memberCount: 80,
    leads: 'Quách Hoa Trí (0905346195), Trần Minh Tuấn (0899300409), Huỳnh Hoàng Mai Khôi (0931905004)',
    activities: [
      'Lên ý tưởng, kịch bản chương trình & sân khấu biểu diễn',
      'Điều phối nhân sự, hậu cần và quản trị rủi ro sự kiện',
      'Tổ chức các hoạt động Teambuilding & Bonding'
    ],
    roles: 'Event Coordinators, Stage Managers, Logistics Leads'
  },

  // --- CỘNG ĐỒNG & ẨM THỰC ---
  f2k: {
    id: 'f2k',
    prefix: 'F2K',
    nameEn: "FPT's Kindness Krew",
    nameVi: 'CLB Thiện nguyện F2K',
    group: 'Cộng đồng',
    subgroup: 'Thiện nguyện',
    boothNumber: 6,
    floor: 3,
    themeColor: '#10b981',
    icon: '🤝',
    logoId: '1PgXZLDcPLzCwtcQGwh7D8ymNnwxzVKo5',
    logoUrl: '/assets/clubs/logos/f2k.png',
    backdropId: '1Mh9wGRreln6S_KVutN8tJLfv16SLsBx7',
    backdropLocalPath: '/assets/clubs/backdrops/f2k_backdrop.png',
    slogan: 'Lan Tỏa Yêu Thương - Sẻ Chia Trách Nhiệm',
    description: 'Tổ chức các chiến dịch tình nguyện ý nghĩa, tiếp sức mùa thi, quyên góp sách vở cho trẻ em vùng cao và các hoạt động bảo vệ môi trường.',
    props: 'Áo tình nguyện, Hộp quà',
    costume: 'Quần đen & Áo CLB, Áo tình nguyện',
    videoConcept: 'Trao hộp quà từ tay này sang tay khác',
    officer: 'DiuVT',
    memberCount: 33,
    leads: 'Phạm Quỳnh Nguyên (0914997996), Đỗ Kha (0765170452), Mai Hưng (0335701775)',
    activities: [
      'Chiến dịch Đông Ấm vùng cao & Mùa Hè Xanh',
      'Thăm hỏi mái ấm tình thương và viện dưỡng lão',
      'Các ngày hội đổi rác lấy cây xanh bảo vệ môi trường'
    ],
    roles: 'Điều phối viên tình nguyện, Truyền thông thiện nguyện'
  },
  fenious: {
    id: 'fenious',
    prefix: 'FENIOUS',
    nameEn: 'Cultural Cuisine Club',
    nameVi: 'CLB Văn hoá ẩm thực',
    group: 'Cộng đồng',
    subgroup: 'Ẩm thực',
    boothNumber: 12,
    floor: 3,
    themeColor: '#f97316',
    icon: '🍲',
    logoId: '1zQvn025Xvg7bpmha2kCQ12yfl_20qTU3',
    logoUrl: '/assets/clubs/logos/fenious.png',
    backdropId: '1Bby8NFy7Mbm6Qz0RDAAGzYCRzwQnHc9V',
    backdropLocalPath: '/assets/clubs/backdrops/fenious_backdrop.png',
    slogan: 'Taste The Culture, Feel The Warmth',
    description: 'Nơi gắn kết những tâm hồn yêu ẩm thực, khám phá tinh hoa món ăn truyền thống 3 miền và văn hóa ẩm thực các nước trên thế giới.',
    props: 'Mâm/khay món ăn, Đũa, nồi, gia vị',
    costume: 'Áo Cam FPT + Quần đen + Phụ kiện khăn của CLB',
    videoConcept: 'Mở nắp nồi → hơi nước transition',
    officer: 'DiuVT',
    memberCount: 20,
    leads: 'Lê Trịnh Trà My (0813987995), Lê Hoàng Gia Hân (0777443844), Đỗ Bá Tuấn Kiệt (0799456400)',
    activities: [
      'Hội thi nấu ăn sinh viên MasterChef FPTU',
      'Trải nghiệm và review ẩm thực đặc sản Đà Nẵng',
      'Giao lưu làm bánh, pha chế thức uống và workshop dinh dưỡng'
    ],
    roles: 'Đầu bếp sinh viên, Reviewer ẩm thực, Hậu cần trải nghiệm'
  },

  // --- NGHỆ THUẬT & ÂM NHẠC ---
  tia: {
    id: 'tia',
    prefix: 'TIA',
    nameEn: 'FPT Traditional Instruments Abide Club',
    nameVi: 'CLB Nhạc cụ dân tộc TIA',
    group: 'Nghệ Thuật',
    subgroup: 'Nhạc cụ',
    boothNumber: 21,
    floor: 3,
    themeColor: '#b45309',
    icon: '🪕',
    logoId: '1CyimauP7mvta0KpK9prf5XBypfnbYBHS',
    logoUrl: '/assets/clubs/logos/tia.png',
    backdropId: '1sIXYaKv1SceiplR9vKafRbUKb-BILec7',
    backdropLocalPath: '/assets/clubs/backdrops/tia_backdrop.png',
    slogan: 'Gìn Giữ Hồn Quê - Thăng Hoa Âm Sắc',
    description: 'Tự hào lưu giữ và lan tỏa tình yêu đối với các nhạc cụ truyền thống Việt Nam: Đàn Tranh, Đàn Bầu, Đàn Nhị, Sáo Trúc, T’rưng trong môi trường đại học hiện đại.',
    props: 'Đàn Tranh, đàn Tỳ Bà, Sáo trúc, nón lá',
    costume: 'Quần trắng + Áo CLB và Áo Dài',
    videoConcept: 'Tay gảy đàn → âm thanh tạo sóng effect',
    officer: 'DiuVT',
    memberCount: 47,
    leads: 'Trần Thị Hoài Trang (0349484138), Hoàng Thị Như Ý (0904798437), Huỳnh Văn Minh Khải (0901147950)',
    activities: [
      'Biểu diễn hòa tấu nhạc cụ dân tộc tại các lễ khai giảng, hội nghị',
      'Phối khí kết hợp nhạc cụ dân tộc và phong cách hiện đại (EDM/Pop)',
      'Lớp học đàn tranh, sáo trúc miễn phí cho tân sinh viên'
    ],
    roles: 'Nhạc công, Nghệ sĩ hòa tấu, Biên đạo âm nhạc'
  },
  rhythm: {
    id: 'rhythm',
    prefix: 'RHYTHM',
    nameEn: 'RHYTHM',
    nameVi: 'Xưởng làm nhạc RHYTHM',
    group: 'Nghệ Thuật',
    subgroup: 'Sản xuất âm nhạc',
    boothNumber: 2,
    floor: 3,
    themeColor: '#8b5cf6',
    icon: '🎵',
    logoId: '18agQO3vHp2bih-zeCjgKC-1ddHGQ3G73',
    logoUrl: '/assets/clubs/logos/rhythm.jpg',
    backdropId: '1qjaHzlO79tSkzZTtu0RhwgH52cF_gead',
    backdropLocalPath: '/assets/clubs/backdrops/rhythm_backdrop.png',
    slogan: 'Feel The Beat, Create The Hit',
    description: 'Studio âm nhạc của các Producers, Beatmakers, Rapper và Ca sĩ FPTU. Nơi sản xuất các bản thu âm, ca khúc chủ đề và biểu diễn live acoustic.',
    props: 'Guitar, Microphone, Headphone',
    costume: 'Áo trắng + Quần/váy trắng + Khoác áo CLB',
    videoConcept: 'Nhấn pad → beat visual xuất hiện',
    officer: 'AnhTD',
    memberCount: 45,
    leads: 'Nguyễn Phú Trọng (0774466206), Bùi Hà Thiên (0986445944), Nguyễn Thị Khánh Ngân (0775405650)',
    activities: [
      'Sản xuất âm nhạc, thu âm và mix/mastering bài hát',
      'Đêm nhạc Acoustic chillout tại khuôn viên trường',
      'Sáng tác các bài hát chủ đề đại diện cho sinh viên FPTU'
    ],
    roles: 'Music Producers, Vocalists, Rappers, Audio Engineers'
  },
  mic: {
    id: 'mic',
    prefix: 'MIC',
    nameEn: "MIC's Home - FUDA MC Club",
    nameVi: 'CLB Dẫn chương trình & Hùng biện',
    group: 'Nghệ Thuật',
    subgroup: 'MC',
    boothNumber: 17,
    floor: 3,
    themeColor: '#0284c7',
    icon: '🎙️',
    logoId: '1wMHAtxP24L_DG_wR_4AuQpR0u94Wtann',
    logoUrl: '/assets/clubs/logos/mic.png',
    backdropId: '1MfS9h7I-NE_YIZ_c4fSiWjjgkaxXhV7M',
    slogan: 'Giọng Nói Kết Nối Triệu Trái Tim',
    description: 'Đào tạo kỹ năng làm chủ sân khấu, dẫn chương trình truyền hình, sự kiện và kỹ năng hùng biện tự tin trước công chúng.',
    props: 'Micro, Cue card',
    costume: 'Áo trắng + quần trắng',
    videoConcept: 'Micro đưa sát camera → transition',
    officer: 'AnhTD',
    memberCount: 28,
    leads: 'Phan Đỗ Minh Lý (0376376436), Đặng Hồng Phúc (0797115036), Đào Nguyễn Vân Quỳnh (0859068252)',
    activities: [
      'Cầm trịch vị trí MC tại toàn bộ sự kiện chính khóa của trường',
      'Cuộc thi Tìm kiếm tài năng MC & Hùng biện sinh viên',
      'Tập luyện kỹ năng xử lý tình huống và kiểm soát giọng nói'
    ],
    roles: 'Sự kiện MC, Voice Talents, Diễn giả trẻ'
  },
  dfp: {
    id: 'dfp',
    prefix: 'DfP',
    nameEn: 'Dance for Passion',
    nameVi: 'CLB Nhảy DfP',
    group: 'Nghệ Thuật',
    subgroup: 'Nhảy hiện đại',
    boothNumber: 8,
    floor: 3,
    themeColor: '#e11d48',
    icon: '💃',
    logoId: '16Pjuj2uwhjNiMgvcXuT72z_qhAFP3jjY',
    logoUrl: '/assets/clubs/logos/dfp.png',
    backdropId: '1f_gSU9owoR767PSZ7h-aDVoory1mxqFV',
    backdropLocalPath: '/assets/clubs/backdrops/dfp_backdrop.png',
    slogan: 'Dance Your Heart Out',
    description: 'CLB vũ đạo hàng đầu FPTU Đà Nẵng, quy tụ các vũ công nhiệt huyết với đa dạng thể loại: Hip-hop, Choreography, K-pop Dance Cover, Jazz Funk.',
    props: 'Loa/boombox, Headphone, LED',
    costume: 'Áo CLB Đỏ',
    videoConcept: 'Beat drop → cả nhóm xuất hiện',
    officer: 'DiuVT',
    memberCount: 25,
    leads: 'Nguyễn Ngọc Thiên Ân (0899863905), Nguyễn Trần Hoàng Ngân (0702715637), Trần Dương Huy (0934091535)',
    activities: [
      'Trình diễn tại các sân khấu đại nhạc hội và ngày hội sinh viên',
      'Thi đấu các giải Dance Battle khu vực miền Trung',
      'Sản xuất các video Dance Showcase chất lượng cao'
    ],
    roles: 'Dancers, Choreographers, Video Planners'
  },
  noise_makers: {
    id: 'noise_makers',
    prefix: 'Noise Makers',
    nameEn: 'Noise Makers',
    nameVi: 'CLB Vũ đạo & Street Dance',
    group: 'Nghệ Thuật',
    subgroup: 'Nhảy đường phố',
    boothNumber: 9,
    floor: 3,
    themeColor: '#a855f7',
    icon: '🕺',
    logoId: '1R0DASAeCd2goaF782z0l0hBGVKr_xNHm',
    logoUrl: '/assets/clubs/logos/noise_makers.jpg',
    backdropId: '1R0DASAeCd2goaF782z0l0hBGVKr_xNHm',
    backdropLocalPath: '/assets/clubs/backdrops/noise_makers_backdrop.png',
    slogan: 'Make Some Noise, Break The Floor',
    description: 'Đậm chất văn hóa đường phố với Popping, Locking, Breaking và Waacking. Đam mê tự do, bùng nổ năng lượng và tinh thần đoàn kết anh em.',
    props: 'Boombox, đồ Street Dance',
    costume: 'Đồ nhảy màu đen và cam',
    videoConcept: 'Cypher và street battle bùng nổ',
    officer: 'HoaNT',
    memberCount: 23,
    leads: 'Lê Thị Hoài Thương (0798966758), Nguyễn Ngọc Bảo Trâm (0899088270), Nguyễn Hồ Ngọc Hân (0886617207)',
    activities: [
      'Giao lưu Street Dance Jam và Cypher hàng tuần',
      'Thi đấu vũ đạo đường phố tại các giải quy mô toàn quốc',
      'Workshop kỹ thuật nhảy cơ bản cho người mới bắt đầu'
    ],
    roles: 'B-boys, B-girls, Freestylers, Battle Dancers'
  },

  // --- THỂ THAO (Đại diện gian hàng & Bảng vinh danh) ---
  fufc: {
    id: 'fufc',
    prefix: 'FUFC',
    nameEn: 'FPTU Football Club',
    nameVi: 'CLB Bóng đá FPTU',
    group: 'Thể thao',
    subgroup: 'Bóng',
    boothNumber: 14,
    floor: 3,
    themeColor: '#16a34a',
    icon: '⚽',
    slogan: 'Đam Mê Bất Tận Trên Sân Cỏ',
    description: 'Đội tuyển bóng đá nam và nữ đại diện cho FPTU tại các giải đấu sinh viên toàn thành phố, duy trì tập luyện tại Sân bóng đá cỏ nhân tạo FUDA.',
    props: 'Bóng đá, Áo đấu, cờ góc',
    costume: 'Đồ đá bóng, tất cổ cao, giày đá bóng',
    videoConcept: 'Sút bóng thẳng vào camera → cut',
    officer: 'DiuVT',
    memberCount: 26,
    leads: 'Nguyễn Khải Minh Trí, Nguyễn Văn Lộc, Trịnh Đăng Khoa',
    activities: [
      'Giải bóng đá FPTU Champions League thường niên',
      'Tập luyện chuyên môn và thi đấu giao hữu hàng tuần',
      'Đại diện trường tham gia giải bóng đá sinh viên Đà Nẵng'
    ],
    roles: 'Cầu thủ, Huấn luyện viên sinh viên, Hậu cần thể thao'
  },
  fhg: {
    id: 'fhg',
    prefix: 'FHG',
    nameEn: 'FUDA Hoops Gene',
    nameVi: 'CLB Bóng rổ FPTU',
    group: 'Thể thao',
    subgroup: 'Bóng',
    boothNumber: 3,
    floor: 3,
    themeColor: '#ea580c',
    icon: '🏀',
    logoId: '1ehsmp0V1AQSDNJcH1CedkYq3D7oXu_g0',
    logoUrl: '/assets/clubs/logos/fhg.png',
    backdropUrl: 'https://drive.google.com/drive/folders/1VFvGQelH-JG6hEqVMbO_QJjJW9QAV-pP',
    slogan: 'Shoot For The Stars',
    description: 'Cộng đồng bóng rổ năng động với sân tập bóng rổ tiêu chuẩn tại Khu Thể Thao FUDA. Đam mê những cú 3 điểm và những pha bứt phá trên sân.',
    props: 'Bóng rổ',
    costume: 'Đồ bóng rổ thể thao',
    videoConcept: 'Bóng bounce → camera follow',
    officer: 'AnhTD',
    memberCount: 25,
    activities: [
      'Giải bóng rổ 3x3 và 5x5 nội bộ FPTU',
      'Giao hữu với các CLB bóng rổ đại học trên địa bàn',
      'Buổi tập kỹ năng ném rổ, phòng ngự và thể lực'
    ],
    roles: 'Ballers, Trọng tài sinh viên, Ban Truyền thông Thể thao'
  },
  fub: {
    id: 'fub',
    prefix: 'FUB',
    nameEn: 'FUDA Badminton Club',
    nameVi: 'CLB Cầu lông FPTU',
    group: 'Thể thao',
    subgroup: 'Cầu lông',
    boothNumber: 22,
    floor: 3,
    themeColor: '#059669',
    icon: '🏸',
    logoId: '1vgozktL98pzcRCkZMViSr3-8hVcfbHck',
    logoUrl: '/assets/clubs/logos/fub.png',
    backdropId: '1W9kT9KwZIV9rk0_BFL05F3DcQ8dAur-9',
    backdropLocalPath: '/assets/clubs/backdrops/fub_backdrop.png',
    slogan: 'Vung Vợt Đam Mê - Cháy Cùng Đồng Đội',
    description: 'Nơi gặp gỡ của những bạn trẻ đam mê cầu lông, rèn luyện sức khỏe, kỹ thuật đập cầu và tham gia các giải đấu phong trào.',
    props: 'Vợt + cầu, Lưới, băng cổ tay',
    costume: 'Áo CLB và Quần thể thao',
    videoConcept: 'Đập cầu → cầu bay xuyên frame',
    officer: 'HoaNT',
    memberCount: 29,
    leads: 'Lê Ngọc Hùng (0932501010), Nguyễn Thị Hiền Giang (0829533746), Phạm Phú Hoàng (0905127518)',
    activities: [
      'Giải cầu lông FPTU Open thường niên',
      'Sinh hoạt tập luyện kỹ thuật đánh đơn, đánh đôi',
      'Giao lưu giao hữu thể thao cuối tuần'
    ],
    roles: 'Vận động viên, Trọng tài, Hậu cần sân bãi'
  },
  fdn: {
    id: 'fdn',
    prefix: 'FDN',
    nameEn: 'Nunchaku Club',
    nameVi: 'CLB Đức Nam Nhị Khúc Côn',
    group: 'Thể thao',
    subgroup: 'Võ thuật',
    boothNumber: 19,
    floor: 3,
    themeColor: '#ca8a04',
    icon: '🥢',
    logoId: '12RDLHzLATJz33sKM0YNlW59FR-1Bc6iF',
    logoUrl: '/assets/clubs/logos/fdn.png',
    backdropUrl: 'https://drive.google.com/drive/folders/1gxSI3c_-q-G3C36Z0PeFH-EWmGdNeUNs',
    slogan: 'Tốc Độ, Chuẩn Xác & Tinh Thần Thượng Võ',
    description: 'Nghiên cứu và tập luyện môn nghệ thuật côn nhị khúc, rèn luyện sự dẻo dai, phản xạ thần tốc và tinh thần kỷ luật tự giác.',
    props: 'Trường Thiết Lĩnh, Trường Côn, Côn Nhị Khúc',
    costume: 'Quần đen & Áo CLB võ thuật',
    videoConcept: 'Spin nunchaku → motion blur transition',
    officer: 'AnhTD',
    memberCount: 20,
    leads: 'Đặng Thị Kim Long (0328265729), Bùi Bảo Duy (0825167018), Văn Trần Hoài Dân (0363141626)',
    activities: [
      'Biểu diễn côn nhị khúc nghệ thuật tại các lễ hội',
      'Luyện tập kỹ thuật cơ bản và nâng cao',
      'Giao lưu võ thuật liên CLB'
    ],
    roles: 'Võ sinh, Nghệ sĩ biểu diễn côn nhị khúc'
  },
  vct: {
    id: 'vct',
    prefix: 'VCT',
    nameEn: 'VCT - FPTU Club',
    nameVi: 'CLB Võ Cổ Truyền FPTU',
    group: 'Thể thao',
    subgroup: 'Võ thuật',
    boothNumber: 11,
    floor: 3,
    themeColor: '#b91c1c',
    icon: '🥋',
    logoId: '1nbz-N9gsVDTqD-JvY2P4k4L4ZtNFiWRF',
    logoUrl: '/assets/clubs/logos/vct.png',
    backdropId: '1Gn8Sekri954niLHLVFusqGI5QaOXOVBI',
    backdropLocalPath: '/assets/clubs/backdrops/vct_backdrop.png',
    slogan: 'Hào Khí Võ Việt - Tôn Sư Trọng Đạo',
    description: 'Gìn giữ và phát huy tinh hoa võ học dân tộc Việt Nam qua các bài quyền, thế đánh tự vệ và tinh thần thượng võ kiên cường.',
    props: 'Đao, kiếm, Cờ Hội võ cổ truyền',
    costume: 'Võ phục Võ cổ truyền',
    videoConcept: 'Một động tác quyền → freeze frame',
    officer: 'HoaNT',
    memberCount: 16,
    leads: 'Trương Thị Diễm Phúc (0386372693), Dương Trong (0367137371), Trần Đại Nghĩa (0899877515)',
    activities: [
      'Tập luyện các bài quyền truyền thống và đối kháng',
      'Tham gia thi đấu các giải võ cổ truyền sinh viên',
      'Huấn luyện kỹ năng tự vệ cho nữ sinh viên'
    ],
    roles: 'Võ sinh, Đội tuyển thi đấu đối kháng'
  },
  fvc: {
    id: 'fvc',
    prefix: 'FVC',
    nameEn: 'FPTU Vovinam Club',
    nameVi: 'CLB Vovinam FPTU',
    group: 'Thể thao',
    subgroup: 'Võ thuật',
    boothNumber: 18,
    floor: 3,
    themeColor: '#2563eb',
    icon: '🥋',
    logoId: '1fsv-axA07tc8dpYUcPaN9bzmEdI0WV0H',
    logoUrl: '/assets/clubs/logos/fvc.png',
    backdropId: '1rRCZXDo72mnry3-jhPxTU-lQgPFcW8zY',
    slogan: 'Việt Võ Đạo - Bàn Tay Thép Đặt Lên Trái Tim Từ Ái',
    description: 'CLB Vovinam đại diện cho môn học đặc trưng truyền thống của sinh viên FPTU, nổi tiếng với các đòn chân tấn công và tinh thần Việt Võ Đạo.',
    props: 'Côn, kiếm, Cờ Vovinam',
    costume: 'Võ phục Vovinam xanh dương truyền thống',
    videoConcept: 'Động tác đòn chân đặc trưng → camera orbit',
    officer: 'AnhTD',
    memberCount: 24,
    leads: 'Nguyễn Cao Văn Nhân (0813044200), Nguyễn Ngọc Bảo Trâm (0899088270), Nguyễn Thành Luân (0972764086)',
    activities: [
      'Đại hội võ thuật Vovinam toàn quốc FPT Edu',
      'Biểu diễn đòn chân kẹp cổ ngoạn mục tại các ngày hội trường',
      'Hỗ trợ luyện tập môn học Giáo dục thể chất Vovinam'
    ],
    roles: 'Việt Võ Sinh, Huấn luyện viên thể chất'
  }
};
